### ISSUE TITLE
Page per method

### ISSUE THREAD

**Issue by zzak** [rails/sdoc#203]
Methods are currently only accessible from the anchor links on class and module pages.

A common request is to have a specific page for each method, this might also help improve SEO results.

**Comment by chris-hewitt** [comment]
I just stumbled across this thread and noticed the concern about SEO, and that we might still be unsure what the problem is.

Isn't the main problem that the guides are constantly linking to new URLs? For example, on https://guides.rubyonrails.org/routing.html:
- Desired: It links to https://api.rubyonrails.org/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resources, building that PageRank strength for 10+ years
- Actual: It links to https://api.rubyonrails.org/v7.1.3/classes/ActionDispatch/Routing/Mapper/Resources.html#method-i-resources, for several months, then never again.

Forgive me if this has already been discussed elsewhere!

**Comment by p8** [comment]
Hmm, interesting @chris-hewitt 
We might want to add a case here when running the current version:
https://github.com/rails/rails/blob/316338acf76c34b529e7d883a916ace798ad8efa/guides/rails_guides/markdown/renderer.rb#L136

Although it could be we move the last version of the guides to a version subdir whenever a new version is released. We prefer to link to the same version of the API docs from the guides.

**Comment by chris-hewitt** [comment]
I think that's spot on, @p8.
We could still link [versioned guide] -> [versioned api] as these are essentially archived docs of specific rails versions. But if the current pages are all "clean" urls linking to other "clean" urls, I think that might make a difference. This is covered more [here](https://webmasters.stackexchange.com/questions/99867/how-to-correctly-mark-up-different-versions-of-the-same-document-which-are-non-c), [here](https://webmasters.stackexchange.com/questions/109113/versioned-pages-making-sure-google-points-to-the-current), [here](https://stackoverflow.com/questions/39913212/link-rel-canonical-should-different-user-guide-versions-use-the-same-canonica).

Other things to consider:

- Having a link to the current "clean" version of an API page, from each of its "versioned" versions, would also probably go a long way. This is another way that sites like APIDock have an advantage. It's also just a useful feature for users. I know this has already been requested and probably already in the works - just reiterating.

- Canonicalization can be an option but I'm not sure it's something we need to consider. [More info](https://developers.google.com/search/docs/crawling-indexing/canonicalization)

- Google's URL Inspection Tool (as described [here](https://developers.google.com/search/docs/fundamentals/seo-starter-guide#googleseeyourpage)) may also provide some useful insight. It must be run by someone who has access to do the DNS verification.

**Comment by zzak** [comment]
I'm not sure there is going to be any action taken here. There are plans for a refresh, and figuring out how to improve our SEO, and per-method pages are included in the feedback we've received. So I'm not sure there is value in keeping this issue open.
