### ISSUE TITLE
Methods not showing up in search results

### ISSUE THREAD

**Issue by p8** [rails/sdoc#330]
When I search for `render` I'm not seeing any render methods in the results:
<img width="455" alt="image" src="https://github.com/rails/sdoc/assets/28561/0ffd995b-5435-4b41-9f82-4e2bfef36a1e">

**Comment by jonathanhefner** [comment]
Modules are ranked above methods in search results.  This is because there are "escape hatches" to search for methods, but no equivalent escape hatch for modules.  Try searching for "#render", ".render", or "render(":

![results](https://github.com/rails/sdoc/assets/771968/67e00f00-6408-40de-90d8-6f48dd2bf406)

I've submitted #331 to add a tip about this.
